# Generated by Django 4.0.5 on 2022-06-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='accounts',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
