# Generated by Django 4.0.5 on 2022-06-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_name_accounts_first_name_accounts_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
