# Generated by Django 4.0.5 on 2022-06-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accounts_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='email',
            field=models.CharField(max_length=12, verbose_name='\\b[\\w.-]+@[\\w.-]+.\\w{2,4}\\b'),
        ),
    ]
