# Generated by Django 4.0.5 on 2022-06-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='pics')),
                ('description', models.CharField(max_length=2555)),
                ('price', models.CharField(max_length=255)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
