# Generated by Django 4.0.5 on 2022-06-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=2555)),
            ],
        ),
    ]
