# Generated by Django 4.0.5 on 2022-06-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_description_alter_about_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
